export default function DeepCurrent() {
  return (
    <section className="relative py-20 px-6">
      <div className="max-w-6xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-6xl font-bold mb-6">
            <span className="bg-gradient-to-r from-blue-400 to-cyan-500 bg-clip-text text-transparent">
              Deep Current Flow
            </span>
          </h2>
          <p className="text-xl text-blue-200/70 max-w-3xl mx-auto">
            Navigate through the powerful underwater currents that carry bioluminescent data across oceanic networks.
          </p>
        </div>

        {/* Current Flow Features */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          <div className="bg-gradient-to-br from-cyan-900/20 to-teal-900/20 p-8 rounded-2xl border border-cyan-500/20 hover:border-cyan-400/40 transition-all duration-300 animate-bio-float">
            <div className="text-4xl mb-4">🌊</div>
            <h3 className="text-2xl font-bold mb-4 text-cyan-300">Thermal Layers</h3>
            <p className="text-cyan-200/70 leading-relaxed mb-4">
              Temperature-stratified currents that create natural data highways through different ocean depths.
            </p>
            <div className="text-sm text-cyan-300/60">Speed: 2.5 km/h</div>
          </div>

          <div className="bg-gradient-to-br from-teal-900/20 to-blue-900/20 p-8 rounded-2xl border border-teal-500/20 hover:border-teal-400/40 transition-all duration-300 animate-bio-drift">
            <div className="text-4xl mb-4">🌀</div>
            <h3 className="text-2xl font-bold mb-4 text-teal-300">Spiral Vortex</h3>
            <p className="text-teal-200/70 leading-relaxed mb-4">
              Rotating water masses that amplify bioluminescent signals and create echo chambers.
            </p>
            <div className="text-sm text-teal-300/60">Rotation: 0.3 RPM</div>
          </div>

          <div className="bg-gradient-to-br from-blue-900/20 to-cyan-900/20 p-8 rounded-2xl border border-blue-500/20 hover:border-blue-400/40 transition-all duration-300 animate-bio-spiral">
            <div className="text-4xl mb-4">⚡</div>
            <h3 className="text-2xl font-bold mb-4 text-blue-300">Bio-Electric</h3>
            <p className="text-blue-200/70 leading-relaxed mb-4">
              Electrically charged currents generated by marine life that power our luminescent systems.
            </p>
            <div className="text-sm text-blue-300/60">Output: 150V</div>
          </div>
        </div>

        {/* Ocean Depth Zones */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <div className="text-center p-6 bg-gradient-to-br from-cyan-900/10 to-teal-900/10 rounded-xl border border-cyan-500/20">
            <div className="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-cyan-400/20 to-teal-400/20 rounded-full flex items-center justify-center border border-cyan-400/30 animate-bio-pulse">
              <span className="text-cyan-400 text-2xl">🌊</span>
            </div>
            <h5 className="font-bold text-cyan-300 mb-2">Surface Zone</h5>
            <p className="text-cyan-200/60 text-sm">0-200m depth</p>
          </div>
          <div className="text-center p-6 bg-gradient-to-br from-teal-900/10 to-blue-900/10 rounded-xl border border-teal-500/20">
            <div className="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-teal-400/20 to-blue-400/20 rounded-full flex items-center justify-center border border-teal-400/30 animate-bio-glow">
              <span className="text-teal-400 text-2xl">🐠</span>
            </div>
            <h5 className="font-bold text-teal-300 mb-2">Twilight Zone</h5>
            <p className="text-teal-200/60 text-sm">200-1000m depth</p>
          </div>
          <div className="text-center p-6 bg-gradient-to-br from-blue-900/10 to-cyan-900/10 rounded-xl border border-blue-500/20">
            <div className="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-blue-400/20 to-cyan-400/20 rounded-full flex items-center justify-center border border-blue-400/30 animate-bio-crystal">
              <span className="text-blue-400 text-2xl">🦑</span>
            </div>
            <h5 className="font-bold text-blue-300 mb-2">Midnight Zone</h5>
            <p className="text-blue-200/60 text-sm">1000-4000m depth</p>
          </div>
          <div className="text-center p-6 bg-gradient-to-br from-cyan-900/10 to-blue-900/10 rounded-xl border border-cyan-500/20">
            <div className="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-cyan-400/20 to-blue-400/20 rounded-full flex items-center justify-center border border-cyan-400/30 animate-bio-fade">
              <span className="text-cyan-400 text-2xl">🕳️</span>
            </div>
            <h5 className="font-bold text-cyan-300 mb-2">Abyssal Zone</h5>
            <p className="text-cyan-200/60 text-sm">4000m+ depth</p>
          </div>
        </div>
      </div>
    </section>
  );
} 